"""empty message

Revision ID: 3c1244fb2a9b
Revises: None
Create Date: 2014-11-22 15:01:23.306029

"""

# revision identifiers, used by Alembic.
revision = '3c1244fb2a9b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prjID', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
