"""empty message

Revision ID: 52b170293da
Revises: 3c1244fb2a9b
Create Date: 2014-11-23 10:07:39.452625

"""

# revision identifiers, used by Alembic.
revision = '52b170293da'
down_revision = '3c1244fb2a9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
